## Below 2 functions cache the inverse of a matrix, so
## if matrix doesn't change, inverse doesn't have to be 
## recomputed since it's a costly computation.

## makeCacheMatrix function creates a special "matrix"
## object that can cache its inverse.

makeCacheMatrix <- function(x = matrix()) {
        invert <- NULL
        
        set <- function(y) {
                x <<- y
                invert <<- NULL
        }
        
        get <- function() x
        setinv <- function(solve) invert <<- solve
        getinv <- function() invert
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## cacheSolve function computes inverse of matrix
## generated by makeCacheMatrix function above. If
## matrix's inverse has already been computed,
## cacheSolve will retrieve answer from cache.

cacheSolve <- function(x, ...) {
        invert <- x$getinv()
        
        if(!is.null(invert)) {
                message("Getting cached data")
                return(invert)
        }
        
        data <- x$get()
        invert <- solve(data,...)
        x$setinv(invert)
        invert
}
